name: Build library
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    # Usually, this would be called as 'nix build ".?submodules=1#app-esp32" '
    # However, Nix 2.19 has a regression with submodule path handling, hence the odd syntax
    # See https://github.com/NixOS/nix/issues/9530
    - run: nix build "git+file://$(pwd)?shallow=1&submodules=1#lib" 